root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/plainmote ./cmd/plainmote"
  bin = "./tmp/plainmote"
  full_bin = "./tmp/plainmote"
  include_ext = ["go", "html", "css", "js", "json", "toml"]
  exclude_dir = ["tmp", "runtime", ".git", "design", "tools"]
  delay = 500
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true
